# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pro Vice Squad
tagline:          'Stand on the edge, fearless and shine.'
description:      'The blog of a misery vampire.'
baseurl:          /

author:
  name:           'The ProViceSquad team'
  url:            https://twitter.com/provicesquad

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/provicesquad
